fix bug when using callable version_scheme
This fixes bug introduced with 0f1c98d032b421f65c8ef5b1042386a6b64bf0b6,
looking like this:

    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-zfpnaarq/xd-docker/setup.py", line 69, in <module>
        setup_requires=['setuptools_scm'],
      File "/usr/local/lib/python3.4/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/local/lib/python3.4/site-packages/setuptools/dist.py", line 272, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/local/lib/python3.4/distutils/dist.py", line 280, in __init__
        self.finalize_options()
      File "/usr/local/lib/python3.4/site-packages/setuptools/dist.py", line 327, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/local/lib/python3.4/site-packages/setuptools_scm-1.10.2.dev8+ng4835e4d-py3.4.egg/setuptools_scm/integration.py", line 16, in version_keyword
    AttributeError: 'function' object has no attribute 'pop'

Signed-off-by: Esben Haabendal <esben@haabendal.dk>